import {
  Resume,
  CandidateProfile,
  RecruiterAnalysis,
  JobRole,
  RoleFit,
  SkillGapSummary,
  ATSResult,
  JDComparison,
  ProjectAnalysis,
  ResumeImprovement,
  CareerRoadmap,
  InterviewSession,
  ChatMessage,
  HistoryRecord,
} from "../types";

export const mockResume: Resume = {
  id: "res-demo-001",
  originalFilename: "Alex_Rivera_AI_Resume_2025.pdf",
  storedFilename: "9f4a21e4-8b22-45e1-8071-c0e816a782b1.pdf",
  fileSizeBytes: 245760, // 240 KB
  mimeType: "application/pdf",
  sha256Hash: "8e3c49e25d2b78a9c39420658fa134d4a849f3e498d9e9e984cfb7d7b328a9b1",
  rawText: `ALEX RIVERA
Email: alex.rivera@example.com | Phone: +1 (555) 349-2041 | Location: Austin, TX
LinkedIn: linkedin.com/in/alexrivera-demo | GitHub: github.com/alexrivera-ai

SUMMARY
Detail-oriented Artificial Intelligence & Data Science graduate with practical experience in Python, SQL, and applied machine learning. Passionate about developing data-driven predictive systems and seeking an AI Engineer or ML role to contribute to production environments.

EDUCATION
B.Tech in Artificial Intelligence & Data Science
Apex Institute of Technology, Austin, TX | 2021 – 2025

TECHNICAL SKILLS
Languages: Python, SQL, Bash (Basic)
Frameworks & Libraries: NumPy, Pandas, Scikit-learn, Matplotlib, Seaborn
Databases: PostgreSQL, SQLite
Tools & Practices: Git, GitHub, Jupyter Notebook, VS Code, Agile/Scrum
Concepts: Data Cleaning, Feature Engineering, Regression, Classification, Clustering, Neural Networks (Foundations)

PROJECTS
Student Performance Prediction System | Scikit-Learn, Pandas, Seaborn
- Preprocessed demographic and academic records across 1,000+ student profiles using Pandas.
- Implemented and tuned Decision Tree and Random Forest Regressors to forecast final exam grades.
- Generated feature importance plots highlighting study hours as the top predictor.

Customer Churn Classifier | Scikit-Learn, Random Forest, Streamlit
- Trained a machine learning pipeline on telecom customer logs to identify churn risk indicators.
- Handled class imbalance using SMOTE and achieved an 83% validation ROC-AUC score.
- Developed an interactive Streamlit web dashboard for real-time customer parameter simulation.

EXPERIENCE
Machine Learning Intern | DataCore Solutions | Jun 2024 – Aug 2024
- Assisted senior engineers in extracting and cleaning structured customer telemetry data using SQL.
- Built automated exploratory data analysis scripts in Python, reducing team reporting preparation time.
- Researched transformer-based text embeddings for customer feedback sentiment categorization.`,
  cleanText: `ALEX RIVERA...`,
  status: "completed",
  createdAt: "2025-02-15T10:30:00Z",
  updatedAt: "2025-02-15T10:32:00Z",
};

export const mockCandidateProfile: CandidateProfile = {
  id: "prof-demo-001",
  resumeId: "res-demo-001",
  isDemo: true,
  name: "Alex Rivera",
  email: "alex.rivera@example.com",
  phone: "+1 (555) 349-2041",
  location: "Austin, TX",
  linkedinUrl: "https://linkedin.com/in/alexrivera-demo",
  githubUrl: "https://github.com/alexrivera-ai",
  executiveSummary:
    "Detail-oriented Artificial Intelligence & Data Science graduate with practical experience in Python, SQL, and applied machine learning. Passionate about developing data-driven predictive systems and seeking an AI Engineer or ML role to contribute to production environments.",
  yearsOfExperience: 0.5,
  education: [
    {
      institution: "Apex Institute of Technology",
      degree: "B.Tech in Artificial Intelligence & Data Science",
      field: "Artificial Intelligence & Data Science",
      startYear: "2021",
      endYear: "2025",
      gpa: "Not found in resume",
      status: "FOUND",
    },
  ],
  workExperience: [
    {
      company: "DataCore Solutions",
      title: "Machine Learning Intern",
      duration: "Jun 2024 – Aug 2024 (3 mos)",
      location: "Austin, TX (Hybrid)",
      bullets: [
        "Assisted senior engineers in extracting and cleaning structured customer telemetry data using SQL.",
        "Built automated exploratory data analysis scripts in Python, reducing team reporting preparation time.",
        "Researched transformer-based text embeddings for customer feedback sentiment categorization.",
      ],
      technologies: ["Python", "SQL", "Pandas", "Scikit-Learn"],
      status: "FOUND",
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Student Performance Prediction System",
      description:
        "Analyzed academic metrics to predict student examination outcomes using supervised learning regressors.",
      technologies: ["Python", "Pandas", "Scikit-Learn", "Matplotlib", "Seaborn"],
      bullets: [
        "Preprocessed demographic and academic records across 1,000+ student profiles using Pandas.",
        "Implemented and tuned Decision Tree and Random Forest Regressors to forecast final exam grades.",
        "Generated feature importance plots highlighting study hours as the top predictor.",
      ],
      githubUrl: "https://github.com/alexrivera-ai/student-performance-predict",
      metricsPresent: false,
      deploymentPresent: false,
      status: "FOUND",
    },
    {
      id: "proj-2",
      title: "Customer Churn Classifier & Streamlit Dashboard",
      description:
        "Built a churn detection pipeline with SMOTE balancing and deployed a localized interactive Streamlit simulator.",
      technologies: ["Python", "Scikit-Learn", "Random Forest", "Streamlit", "Pandas"],
      bullets: [
        "Trained a machine learning pipeline on telecom customer logs to identify churn risk indicators.",
        "Handled class imbalance using SMOTE and achieved an 83% validation ROC-AUC score.",
        "Developed an interactive Streamlit web dashboard for real-time customer parameter simulation.",
      ],
      githubUrl: "https://github.com/alexrivera-ai/telecom-churn-classifier",
      metricsPresent: true,
      deploymentPresent: false,
      status: "FOUND",
    },
  ],
  certifications: [
    {
      name: "Cloud Practitioner / AWS Certified",
      status: "NOT_FOUND",
    },
  ],
  achievements: [
    "Finalist, Regional Data Analytics Hackathon 2024 (Predictive Modeling Track)",
  ],
  publications: [],
  skills: [
    { name: "Python", category: "Programming", confidence: "FOUND", evidenceSnippet: "Technical Skills & all projects" },
    { name: "SQL", category: "Database", confidence: "FOUND", evidenceSnippet: "DataCore internship & skills list" },
    { name: "Pandas", category: "Data", confidence: "FOUND", evidenceSnippet: "Student Performance & Churn projects" },
    { name: "NumPy", category: "Data", confidence: "FOUND", evidenceSnippet: "Technical skills section" },
    { name: "Scikit-learn", category: "Machine Learning", confidence: "FOUND", evidenceSnippet: "Model training in both projects" },
    { name: "Matplotlib", category: "Data", confidence: "FOUND", evidenceSnippet: "Data visualization in projects" },
    { name: "Git", category: "Tool", confidence: "FOUND", evidenceSnippet: "Technical tools list & GitHub repository links" },
    { name: "Deep Learning", category: "Deep Learning", confidence: "INFERRED", evidenceSnippet: "Conceptual mention under Neural Networks" },
    { name: "PyTorch", category: "Deep Learning", confidence: "NOT_FOUND" },
    { name: "Docker", category: "DevOps", confidence: "NOT_FOUND" },
    { name: "Cloud Deployment (AWS/GCP)", category: "Cloud", confidence: "NOT_FOUND" },
    { name: "MLOps / CI/CD", category: "MLOps", confidence: "NOT_FOUND" },
  ],
  missingSections: [
    "Certifications",
    "Production Deployment Evidence",
    "Quantified Business Outcomes",
  ],
  createdAt: "2025-02-15T10:32:00Z",
};

export const mockRecruiterAnalysis: RecruiterAnalysis = {
  id: "analysis-demo-001",
  resumeId: "res-demo-001",
  overallScore: 78,
  atsReadiness: 76,
  topRole: "AI Engineer",
  topRoleFitScore: 84,
  executiveSummary:
    "Alex demonstrates a well-grounded analytical base in Python, relational SQL, and classical tabular machine learning workflows. As an entry-level candidate, the profile clearly reflects hands-on data manipulation and feature engineering. However, for a competitive AI Engineer role, senior recruiters will note the absence of deep learning framework implementations (PyTorch/TensorFlow) and containerized deployment infrastructure (Docker, cloud APIs).",
  signals: [
    {
      id: "sig-1",
      type: "green",
      title: "Strong Python & Structured Data Foundation",
      description: "Demonstrates consistent application of Python, Pandas, and SQL across both academic coursework and internship deliverables.",
      evidence: "Verified in DataCore internship telemetry extraction & Scikit-learn project pipelines.",
    },
    {
      id: "sig-2",
      type: "yellow",
      title: "Project Descriptions Lack Measurable Business Impact",
      description: "Project bullet points detail what technologies were used but lack metrics demonstrating business efficiency or scale.",
      evidence: "Student Performance project states 'implemented decision trees' without noting inference speed, dataset scale, or impact.",
    },
    {
      id: "sig-3",
      type: "red",
      title: "No Cloud Deployment or Containerization Evidence",
      description: "Neither Docker, REST/FastAPI endpoints, nor cloud providers (AWS, GCP) are mentioned. Models currently reside only in local scripts.",
      evidence: "Not found in resume across all projects and internship entries.",
    },
    {
      id: "sig-4",
      type: "yellow",
      title: "Deep Learning Experience Appears Theoretical Only",
      description: "Resume lists 'Neural Networks (Foundations)' under concepts, but exhibits no project using PyTorch or TensorFlow.",
      evidence: "Only Scikit-learn tabular models appear in project implementations.",
    },
  ],
  recruiterQuestions: [
    "Why did you choose Random Forest over XGBoost or LightGBM for the churn classification project?",
    "How would you deploy your Streamlit churn predictor to serve 500 concurrent HTTP requests with sub-100ms latency?",
    "Can you walk me through how you handled the severe class imbalance in the telecom dataset before applying SMOTE?",
  ],
  missingInformation: [
    "GPA / Academic Honors: Not found in resume",
    "Certifications: Not provided",
    "Cloud infrastructure / AWS experience: Not found in resume",
    "Production deployment metrics (latency, QPS, uptime): Not found in resume",
  ],
  priorityActions: [
    "Build and package one deep learning project in PyTorch with FastAPI and Docker.",
    "Add measurable metrics to the Student Performance bullet points (e.g., dataset volume, error reduction rate).",
    "Deploy the Streamlit churn predictor to a public cloud instance (AWS EC2 / Render) and link the live demo.",
  ],
  recommendedNextStep:
    "Follow the 12-week Career Roadmap starting with the PyTorch & Docker inference deployment milestone.",
};

export const mockJobRoles: JobRole[] = [
  {
    id: "role-1",
    roleCode: "ai_engineer",
    displayName: "AI Engineer",
    category: "AI/ML",
    description: "Designs, trains, and deploys intelligent models and AI systems into production software pipelines.",
    experienceExpectations: "0-2 years (Entry) with solid Python, ML algorithms, PyTorch/TensorFlow, and API deployment.",
    commonTools: ["Python", "PyTorch", "FastAPI", "Docker", "Hugging Face", "PostgreSQL"],
    projectExpectations: ["End-to-end model training to API serving", "Evaluation metrics optimization", "Containerized deployment"],
    interviewTopics: ["Model architecture selection", "Overfitting & Regularization", "Inference optimization", "API integration"],
    requiredSkills: ["Python", "Scikit-learn", "PyTorch", "Docker", "SQL", "FastAPI"],
    preferredSkills: ["Hugging Face", "MLflow", "AWS", "Git"],
  },
  {
    id: "role-2",
    roleCode: "ml_engineer",
    displayName: "Machine Learning Engineer",
    category: "AI/ML",
    description: "Bridges the gap between research data science and scalable production software architecture.",
    experienceExpectations: "0-2 years with strong algorithm foundations, feature stores, and CI/CD pipelines.",
    commonTools: ["Python", "Scikit-learn", "PyTorch", "Docker", "MLOps", "SQL"],
    projectExpectations: ["Scalable training pipeline", "Model tracking & registry", "Data drift monitoring"],
    interviewTopics: ["Feature engineering at scale", "Pipeline orchestration", "Latency tradeoffs"],
    requiredSkills: ["Python", "Scikit-learn", "SQL", "Docker", "Git"],
    preferredSkills: ["PyTorch", "Kubernetes", "AWS", "MLflow"],
  },
  {
    id: "role-3",
    roleCode: "genai_engineer",
    displayName: "Generative AI Engineer",
    category: "AI/ML",
    description: "Builds applications leveraging LLMs, retrieval-augmented generation (RAG), and agentic workflows.",
    experienceExpectations: "Foundational ML with modern LLM prompt engineering, LangChain/LlamaIndex, and vector databases.",
    commonTools: ["Python", "LangChain", "OpenAI API", "pgvector / Pinecone", "FastAPI"],
    projectExpectations: ["Production RAG pipeline", "Evaluation benchmark against hallucination", "Vector search"],
    interviewTopics: ["Chunking strategies", "Embeddings distance metrics", "Hallucination prevention"],
    requiredSkills: ["Python", "SQL", "Vector Databases", "Prompt Engineering"],
    preferredSkills: ["LangChain", "FastAPI", "Docker", "PyTorch"],
  },
  {
    id: "role-4",
    roleCode: "data_analyst",
    displayName: "Data Analyst",
    category: "Data",
    description: "Transforms structured business telemetry into actionable insights, dashboards, and KPI metrics.",
    experienceExpectations: "Proficient SQL, advanced Excel/Pandas, and dashboard visualization tools (Tableau, PowerBI).",
    commonTools: ["SQL", "Python", "Pandas", "Tableau", "Power BI", "Excel"],
    projectExpectations: ["Exploratory Data Analysis report", "Interactive business KPI dashboard", "Cohort retention"],
    interviewTopics: ["Complex SQL joins & window functions", "A/B testing basics", "Storytelling with charts"],
    requiredSkills: ["SQL", "Python", "Pandas", "Matplotlib"],
    preferredSkills: ["Power BI", "Tableau", "Seaborn"],
  },
  {
    id: "role-5",
    roleCode: "python_developer",
    displayName: "Python Developer",
    category: "Software",
    description: "Develops robust backend services, automated scripts, and data ingestion services in Python.",
    experienceExpectations: "Deep Python syntax, object-oriented design, relational databases, and testing frameworks.",
    commonTools: ["Python", "FastAPI", "Django", "PostgreSQL", "Git", "Docker"],
    projectExpectations: ["RESTful API backend", "Data ingestion pipeline", "PyTest coverage"],
    interviewTopics: ["Python concurrency", "Decorators & Generators", "Database transactions"],
    requiredSkills: ["Python", "SQL", "Git"],
    preferredSkills: ["FastAPI", "Docker", "PostgreSQL", "PyTest"],
  },
  {
    id: "role-6",
    roleCode: "data_scientist",
    displayName: "Data Scientist",
    category: "Data",
    description: "Extracts predictive insights from raw data using mathematical modeling, statistics, and machine learning.",
    experienceExpectations: "Solid statistical inference, hypothesis testing, feature engineering, and stakeholder communication.",
    commonTools: ["Python", "Pandas", "Scikit-learn", "SQL", "Statistics", "Jupyter"],
    projectExpectations: ["Hypothesis test report", "End-to-end predictive model with business impact"],
    interviewTopics: ["Statistical power", "Bias-Variance tradeoff", "Metric selection (AUC vs F1)"],
    requiredSkills: ["Python", "Pandas", "SQL", "Scikit-learn", "NumPy"],
    preferredSkills: ["PyTorch", "A/B Testing", "Seaborn"],
  },
  {
    id: "role-7",
    roleCode: "backend_developer",
    displayName: "Backend Developer",
    category: "Software",
    description: "Architects scalable server-side systems, relational data structures, and secure client-facing APIs.",
    experienceExpectations: "Strong HTTP protocols, database indexing, caching strategies, and API security.",
    commonTools: ["Python", "PostgreSQL", "FastAPI / Django", "Docker", "Redis"],
    projectExpectations: ["Multi-endpoint CRUD API with authentication", "Database migration pipeline"],
    interviewTopics: ["Database normalization & index tuning", "REST vs GraphQL", "Authentication strategies"],
    requiredSkills: ["Python", "SQL", "Git"],
    preferredSkills: ["FastAPI", "Docker", "PostgreSQL", "Redis"],
  },
  {
    id: "role-8",
    roleCode: "data_engineer",
    displayName: "Data Engineer",
    category: "Data",
    description: "Builds high-throughput ETL pipelines, data warehouses, and batch/streaming data processing jobs.",
    experienceExpectations: "Distributed computing concepts, SQL optimization, data modeling, and orchestration.",
    commonTools: ["Python", "SQL", "Apache Spark", "Airflow", "PostgreSQL", "Docker"],
    projectExpectations: ["Automated ETL ingestion pipeline", "Dimensional star-schema data warehouse"],
    interviewTopics: ["Partitioning & Sharding", "DAG orchestration", "Batch vs Streaming"],
    requiredSkills: ["Python", "SQL", "Git"],
    preferredSkills: ["Docker", "Airflow", "Spark", "PostgreSQL"],
  },
  {
    id: "role-9",
    roleCode: "nlp_engineer",
    displayName: "NLP Engineer",
    category: "AI/ML",
    description: "Specializes in computational linguistics, text classification, transformers, and sequence modeling.",
    experienceExpectations: "Strong tokenization, embeddings, transformer architectures (BERT, RoBERTa), and PyTorch.",
    commonTools: ["Python", "PyTorch", "Hugging Face", "NLTK / Spacy", "Scikit-learn"],
    projectExpectations: ["Custom text classifier or NER pipeline", "Semantic search implementation"],
    interviewTopics: ["Self-attention mechanisms", "Tokenization nuances", "Evaluation metrics (BLEU, ROUGE)"],
    requiredSkills: ["Python", "Scikit-learn", "SQL"],
    preferredSkills: ["PyTorch", "Hugging Face", "Docker"],
  },
  {
    id: "role-10",
    roleCode: "computer_vision_engineer",
    displayName: "Computer Vision Engineer",
    category: "AI/ML",
    description: "Builds deep learning models for image classification, object detection, and visual perception.",
    experienceExpectations: "Convolutional neural networks, OpenCV, PyTorch/TensorFlow, and data augmentation.",
    commonTools: ["Python", "OpenCV", "PyTorch", "YOLO", "Docker"],
    projectExpectations: ["Object detection or segmentation pipeline", "Image preprocessing pipeline"],
    interviewTopics: ["CNN architectures", "Data augmentation techniques", "Edge deployment tradeoffs"],
    requiredSkills: ["Python", "NumPy", "Git"],
    preferredSkills: ["OpenCV", "PyTorch", "Docker"],
  },
  {
    id: "role-11",
    roleCode: "mlops_engineer",
    displayName: "MLOps Engineer",
    category: "AI/ML",
    description: "Automates ML model deployment, monitoring, CI/CD, and pipeline reliability across cloud clusters.",
    experienceExpectations: "DevOps practices applied to machine learning: Docker, Kubernetes, CI/CD, and model tracking.",
    commonTools: ["Docker", "Kubernetes", "MLflow", "GitHub Actions", "Python", "AWS"],
    projectExpectations: ["CI/CD automated retraining pipeline", "Monitoring stack with Prometheus/Grafana"],
    interviewTopics: ["Model drift detection", "Zero-downtime model deployments", "Container orchestration"],
    requiredSkills: ["Python", "Git", "SQL"],
    preferredSkills: ["Docker", "Kubernetes", "MLflow", "CI/CD"],
  },
];

export const mockRoleFits: RoleFit[] = [
  {
    roleCode: "ai_engineer",
    roleName: "AI Engineer",
    category: "AI/ML",
    deterministicScore: 84,
    requiredSkillCoverage: 75,
    preferredSkillCoverage: 50,
    projectRelevanceScore: 85,
    experienceRelevanceScore: 70,
    keywordScore: 80,
    matchedSkills: ["Python", "SQL", "Pandas", "NumPy", "Scikit-learn", "Git"],
    missingSkills: ["PyTorch", "Docker", "FastAPI", "Cloud Deployment"],
    priorityGaps: ["PyTorch (Deep Learning)", "Docker (Containerization)", "FastAPI (Model Serving)"],
    whyItFits:
      "Your resume proves hands-on Python model development, data preprocessing with Pandas, and supervised learning algorithms. You have the foundational math and programming core; closing the PyTorch and containerization gap will position you as an outstanding candidate.",
    recruiterConcerns: [
      "No production inference framework (FastAPI or Flask) shown in project descriptions.",
      "Lack of deep learning frameworks (PyTorch / TensorFlow).",
      "No Docker containerization evidence.",
    ],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 85 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 80 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 75 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 85 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 80 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 70 },
    ],
    recommendedProjects: [
      "PyTorch End-to-End Image or Text Classifier deployed via FastAPI inside a Docker container.",
      "LLM RAG application with pgvector and semantic search.",
    ],
    learningPriorities: ["PyTorch Foundations", "FastAPI Inference REST API", "Docker Containerization"],
  },
  {
    roleCode: "data_analyst",
    roleName: "Data Analyst",
    category: "Data",
    deterministicScore: 89,
    requiredSkillCoverage: 95,
    preferredSkillCoverage: 70,
    projectRelevanceScore: 90,
    experienceRelevanceScore: 80,
    keywordScore: 88,
    matchedSkills: ["Python", "SQL", "Pandas", "NumPy", "Matplotlib", "Seaborn"],
    missingSkills: ["Tableau / Power BI", "Business Dashboarding"],
    priorityGaps: ["Tableau or Power BI Portfolio", "Business Metric Articulation"],
    whyItFits:
      "Your combination of SQL telemetry querying from the internship and rigorous Pandas data manipulation makes you directly competitive for Data Analyst roles.",
    recruiterConcerns: ["Missing enterprise BI tools like Power BI or Tableau."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 70 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 85 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 50 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 30 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 30 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 40 },
    ],
    recommendedProjects: ["Executive Sales or Retention Dashboard using Streamlit or Power BI."],
    learningPriorities: ["Power BI or Tableau", "Cohort Analysis", "Executive Presentation"],
  },
  {
    roleCode: "python_developer",
    roleName: "Python Developer",
    category: "Software",
    deterministicScore: 86,
    requiredSkillCoverage: 80,
    preferredSkillCoverage: 60,
    projectRelevanceScore: 80,
    experienceRelevanceScore: 75,
    keywordScore: 82,
    matchedSkills: ["Python", "SQL", "Git", "PostgreSQL"],
    missingSkills: ["FastAPI / Django", "PyTest", "Docker"],
    priorityGaps: ["Web Framework (FastAPI)", "Unit Testing (PyTest)"],
    whyItFits:
      "Strong Python coding evidence across all projects and internship work. Converting scripts into modular packages and web APIs will immediately unlock backend engineering roles.",
    recruiterConcerns: ["No backend web framework (FastAPI/Django) explicitly listed."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 90 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 70 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 40 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 30 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 75 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 65 },
    ],
    recommendedProjects: ["RESTful API with FastAPI, SQLAlchemy Async, and PyTest coverage."],
    learningPriorities: ["FastAPI Framework", "PyTest & Mocking", "Docker Containers"],
  },
  {
    roleCode: "ml_engineer",
    roleName: "Machine Learning Engineer",
    category: "AI/ML",
    deterministicScore: 81,
    requiredSkillCoverage: 70,
    preferredSkillCoverage: 50,
    projectRelevanceScore: 80,
    experienceRelevanceScore: 70,
    keywordScore: 75,
    matchedSkills: ["Python", "Scikit-learn", "SQL", "Git"],
    missingSkills: ["PyTorch", "Docker", "MLflow", "Kubernetes"],
    priorityGaps: ["Model Pipeline Orchestration", "Containerization (Docker)", "Experiment Tracking"],
    whyItFits: "Demonstrates practical scikit-learn model development and data wrangling.",
    recruiterConcerns: ["Lacks MLOps tooling like MLflow, Docker, or automated pipelines."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 88 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 85 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 85 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 75 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 85 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 80 },
    ],
    recommendedProjects: ["Automated retraining pipeline with MLflow and Docker."],
    learningPriorities: ["Docker for ML", "MLflow Tracking", "Pipeline Automation"],
  },
  {
    roleCode: "data_scientist",
    roleName: "Data Scientist",
    category: "Data",
    deterministicScore: 79,
    requiredSkillCoverage: 80,
    preferredSkillCoverage: 50,
    projectRelevanceScore: 75,
    experienceRelevanceScore: 65,
    keywordScore: 72,
    matchedSkills: ["Python", "Pandas", "NumPy", "Scikit-learn", "SQL"],
    missingSkills: ["A/B Testing", "Advanced Statistics", "Deep Learning"],
    priorityGaps: ["Statistical Hypothesis Testing", "Business Experimentation"],
    whyItFits: "Solid applied machine learning algorithms and exploratory data analysis foundation.",
    recruiterConcerns: ["Needs more evidence of business problem formulation and statistical hypothesis testing."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 80 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 90 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 85 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 65 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 50 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 50 },
    ],
    recommendedProjects: ["A/B test analysis and customer segmentation case study."],
    learningPriorities: ["Experimental Design", "Advanced Statistical Inference"],
  },
  {
    roleCode: "backend_developer",
    roleName: "Backend Developer",
    category: "Software",
    deterministicScore: 72,
    requiredSkillCoverage: 60,
    preferredSkillCoverage: 40,
    projectRelevanceScore: 65,
    experienceRelevanceScore: 60,
    keywordScore: 68,
    matchedSkills: ["Python", "SQL", "Git"],
    missingSkills: ["FastAPI / Django", "Docker", "Database Indexing & Architecture", "Redis"],
    priorityGaps: ["Web Framework", "API Design", "Docker"],
    whyItFits: "Strong foundational Python programming and relational database fundamentals.",
    recruiterConcerns: ["Has not yet built a multi-endpoint RESTful server with authentication."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 90 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 75 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 20 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 20 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 85 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 80 },
    ],
    recommendedProjects: ["E-commerce or task management API with JWT auth and PostgreSQL."],
    learningPriorities: ["FastAPI / Express", "Database Indexing & Transactions", "Docker"],
  },
  {
    roleCode: "data_engineer",
    roleName: "Data Engineer",
    category: "Data",
    deterministicScore: 68,
    requiredSkillCoverage: 60,
    preferredSkillCoverage: 30,
    projectRelevanceScore: 60,
    experienceRelevanceScore: 55,
    keywordScore: 62,
    matchedSkills: ["Python", "SQL", "Git", "PostgreSQL"],
    missingSkills: ["Apache Spark", "Airflow", "Data Warehousing", "Docker"],
    priorityGaps: ["Distributed Computing (Spark)", "Orchestration (Airflow)"],
    whyItFits: "Understands relational querying, schema extraction, and Python data pipelines.",
    recruiterConcerns: ["No exposure to distributed compute or pipeline orchestration frameworks."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 85 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 95 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 40 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 20 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 80 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 85 },
    ],
    recommendedProjects: ["ETL pipeline ingesting public API data into PostgreSQL using Airflow."],
    learningPriorities: ["Apache Airflow", "Data Modeling & Star Schema", "Spark Foundations"],
  },
  {
    roleCode: "nlp_engineer",
    roleName: "NLP Engineer",
    category: "AI/ML",
    deterministicScore: 64,
    requiredSkillCoverage: 50,
    preferredSkillCoverage: 30,
    projectRelevanceScore: 55,
    experienceRelevanceScore: 50,
    keywordScore: 60,
    matchedSkills: ["Python", "Scikit-learn", "Git"],
    missingSkills: ["Transformers / Hugging Face", "PyTorch", "SpaCy / NLTK", "Text Preprocessing"],
    priorityGaps: ["Hugging Face Transformers", "PyTorch", "Tokenization"],
    whyItFits: "Mentions text embeddings research in internship summary.",
    recruiterConcerns: ["Has not built a standalone natural language processing project."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 85 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 75 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 75 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 90 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 75 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 65 },
    ],
    recommendedProjects: ["Fine-tuning a BERT classifier on financial news sentiment."],
    learningPriorities: ["Hugging Face Library", "Tokenization Strategies", "Transformer Architecture"],
  },
  {
    roleCode: "computer_vision_engineer",
    roleName: "Computer Vision Engineer",
    category: "AI/ML",
    deterministicScore: 58,
    requiredSkillCoverage: 40,
    preferredSkillCoverage: 20,
    projectRelevanceScore: 40,
    experienceRelevanceScore: 40,
    keywordScore: 45,
    matchedSkills: ["Python", "NumPy", "Git"],
    missingSkills: ["OpenCV", "PyTorch", "Convolutional Neural Networks", "YOLO"],
    priorityGaps: ["OpenCV", "PyTorch CNNs", "Image Augmentation"],
    whyItFits: "Has numerical programming foundation in Python and NumPy.",
    recruiterConcerns: ["Completely lacks image processing or computer vision portfolio items."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 85 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 60 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 65 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 95 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 75 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 65 },
    ],
    recommendedProjects: ["Real-time webcam object detection using YOLO and OpenCV."],
    learningPriorities: ["OpenCV Fundamentals", "PyTorch CNN Architectures"],
  },
  {
    roleCode: "genai_engineer",
    roleName: "Generative AI Engineer",
    category: "AI/ML",
    deterministicScore: 56,
    requiredSkillCoverage: 40,
    preferredSkillCoverage: 25,
    projectRelevanceScore: 45,
    experienceRelevanceScore: 40,
    keywordScore: 48,
    matchedSkills: ["Python", "SQL", "Git"],
    missingSkills: ["LangChain", "Vector Databases", "Prompt Engineering", "OpenAI APIs"],
    priorityGaps: ["Vector Databases (pgvector/Pinecone)", "RAG Systems", "LangChain/LlamaIndex"],
    whyItFits: "Mentions text embeddings research during internship.",
    recruiterConcerns: ["No RAG pipelines, LLM fine-tuning, or vector indexing projects exhibited."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 85 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 75 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 60 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 80 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 80 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 70 },
    ],
    recommendedProjects: ["RAG documentation query engine using LangChain and pgvector."],
    learningPriorities: ["Vector Database Operations", "RAG Prompt Guardrails", "Embedding Models"],
  },
  {
    roleCode: "mlops_engineer",
    roleName: "MLOps Engineer",
    category: "AI/ML",
    deterministicScore: 51,
    requiredSkillCoverage: 35,
    preferredSkillCoverage: 20,
    projectRelevanceScore: 30,
    experienceRelevanceScore: 35,
    keywordScore: 38,
    matchedSkills: ["Python", "Git", "SQL"],
    missingSkills: ["Docker", "Kubernetes", "MLflow", "CI/CD Workflows", "AWS/GCP"],
    priorityGaps: ["Docker Containers", "CI/CD Automation", "MLflow Tracking"],
    whyItFits: "Solid version control practices with Git and Python scripting.",
    recruiterConcerns: ["Heavy gap in containerization, infrastructure-as-code, and orchestration."],
    radarMetrics: [
      { dimension: "Programming (Python)", candidateScore: 90, benchmarkScore: 85 },
      { dimension: "Data Prep (Pandas/SQL)", candidateScore: 88, benchmarkScore: 75 },
      { dimension: "Classical ML", candidateScore: 82, benchmarkScore: 70 },
      { dimension: "Deep Learning", candidateScore: 40, benchmarkScore: 60 },
      { dimension: "Deployment & Docker", candidateScore: 20, benchmarkScore: 95 },
      { dimension: "Cloud & CI/CD", candidateScore: 15, benchmarkScore: 95 },
    ],
    recommendedProjects: ["GitHub Actions workflow linting, testing, and containerizing a model on push."],
    learningPriorities: ["Docker Fundamentals", "GitHub Actions CI/CD", "MLflow Experiment Tracking"],
  },
];

export const mockSkillGaps: SkillGapSummary = {
  roleCode: "ai_engineer",
  roleName: "AI Engineer",
  totalSkills: 16,
  strongCount: 5,
  intermediateCount: 3,
  needsImprovementCount: 2,
  missingCount: 6,
  categories: [
    "Programming",
    "Data",
    "Machine Learning",
    "Deep Learning",
    "Backend",
    "Databases",
    "Cloud",
    "DevOps",
    "MLOps",
  ],
  items: [
    {
      id: "sg-1",
      skill: "Python",
      category: "Programming",
      currentStatus: "Strong",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Verified in DataCore internship & both Scikit-learn projects.",
      sourceSection: "Skills, Projects & Experience",
      reason: "Demonstrated multi-year academic and practical applied coding.",
      recommendedAction: "Maintain edge by writing clean, modular object-oriented code with type annotations.",
    },
    {
      id: "sg-2",
      skill: "SQL",
      category: "Databases",
      currentStatus: "Strong",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Verified in DataCore internship telemetry extraction.",
      sourceSection: "Experience",
      reason: "Hands-on data extraction and filtering across structured datasets.",
      recommendedAction: "Practice advanced window functions and query optimization benchmarks.",
    },
    {
      id: "sg-3",
      skill: "Pandas & NumPy",
      category: "Data",
      currentStatus: "Strong",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Verified in Student Performance and Churn projects.",
      sourceSection: "Projects",
      reason: "Clean data pipeline implementation with tabular transformations.",
      recommendedAction: "Demonstrate performance optimization (vectorization over loops).",
    },
    {
      id: "sg-4",
      skill: "Scikit-Learn (Supervised ML)",
      category: "Machine Learning",
      currentStatus: "Intermediate",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Applied Decision Trees and Random Forests with validation scores.",
      sourceSection: "Projects",
      reason: "Good grasp of training pipelines, but limited to standard tabular algorithms.",
      recommendedAction: "Expand to gradient boosting (XGBoost, LightGBM) and hyperparameter tuning (Optuna).",
    },
    {
      id: "sg-5",
      skill: "Git & Version Control",
      category: "Programming",
      currentStatus: "Intermediate",
      roleRequirement: "Required",
      importance: "High",
      evidence: "Present in skills list and GitHub profile links.",
      sourceSection: "Skills",
      reason: "Familiarity with standard repo management.",
      recommendedAction: "Contribute to open source or demonstrate multi-branch Git workflow.",
    },
    {
      id: "sg-6",
      skill: "Deep Learning (Neural Networks)",
      category: "Deep Learning",
      currentStatus: "Needs Improvement",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Mentioned only conceptually as 'Neural Networks (Foundations)' in Skills.",
      sourceSection: "Skills",
      reason: "Theoretical exposure without verified code evidence or project architecture.",
      recommendedAction: "Build a convolutional or transformer model from scratch in PyTorch.",
    },
    {
      id: "sg-7",
      skill: "Model Evaluation & Metrics",
      category: "Machine Learning",
      currentStatus: "Needs Improvement",
      roleRequirement: "Required",
      importance: "High",
      evidence: "Reported 83% validation ROC-AUC in churn project; missing confusion matrix/F1 analysis.",
      sourceSection: "Projects",
      reason: "Shows basic validation but lacks precision/recall tradeoff analysis.",
      recommendedAction: "Document precision-recall curves and business cost-benefit matrices.",
    },
    {
      id: "sg-8",
      skill: "PyTorch",
      category: "Deep Learning",
      currentStatus: "Missing",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Not found in resume",
      reason: "Core deep learning framework expected by modern AI engineering teams.",
      recommendedAction: "Implement an end-to-end classification pipeline in PyTorch (DataLoader, Train Loop, Loss).",
    },
    {
      id: "sg-9",
      skill: "Docker",
      category: "DevOps",
      currentStatus: "Missing",
      roleRequirement: "Required",
      importance: "Critical",
      evidence: "Not found in resume",
      reason: "Containerization is required to package model code with dependencies for reproducible deployment.",
      recommendedAction: "Write a Dockerfile packaging a model inference API and test it locally.",
    },
    {
      id: "sg-10",
      skill: "FastAPI / Model Serving",
      category: "Backend",
      currentStatus: "Missing",
      roleRequirement: "Required",
      importance: "High",
      evidence: "Not found in resume",
      reason: "Production AI systems serve predictions over HTTP/gRPC interfaces.",
      recommendedAction: "Wrap your trained churn model in a FastAPI endpoint with Pydantic request validation.",
    },
    {
      id: "sg-11",
      skill: "Cloud Deployment (AWS/GCP)",
      category: "Cloud",
      currentStatus: "Missing",
      roleRequirement: "Preferred",
      importance: "High",
      evidence: "Not found in resume",
      reason: "Production models run on cloud compute instances or serverless containers.",
      recommendedAction: "Deploy your Dockerized model to AWS ECS, Render, or GCP Cloud Run.",
    },
    {
      id: "sg-12",
      skill: "MLOps / CI/CD",
      category: "MLOps",
      currentStatus: "Missing",
      roleRequirement: "Preferred",
      importance: "Medium",
      evidence: "Not found in resume",
      reason: "Automated testing and continuous delivery for machine learning code.",
      recommendedAction: "Configure a GitHub Actions workflow to run unit tests on every Git push.",
    },
  ],
};

export const mockATSResult: ATSResult = {
  overallScore: 76,
  readinessLevel: "Moderate",
  summary:
    "Your resume possesses a clean, standard section layout that will parse smoothly through major ATS engines (Workday, Greenhouse, Lever). However, ATS keyword density for modern AI Engineer roles is diluted by missing framework terms (PyTorch, Docker, FastAPI), and several bullet points lack quantifiable metric syntax.",
  subScores: [
    { name: "Contact & Header Information", score: 95, weight: 15, status: "good", feedback: "Full contact details, email, phone, LinkedIn, and GitHub links detected." },
    { name: "Standard Section Headers", score: 90, weight: 15, status: "good", feedback: "Clear standard headings: Summary, Education, Skills, Projects, Experience." },
    { name: "Metric & Outcome Density", score: 55, weight: 20, status: "warning", feedback: "Only 1 out of 6 bullet points contains a numeric percentage or scale indicator." },
    { name: "Role Keyword Alignment", score: 68, weight: 20, status: "warning", feedback: "Target role 'AI Engineer' requires critical keywords currently absent (PyTorch, Docker)." },
    { name: "Parseability & Clean Layout", score: 88, weight: 10, status: "good", feedback: "Single-column layout with standard text fonts. No unparseable elements." },
    { name: "Action Verb Rigor", score: 75, weight: 10, status: "good", feedback: "Strong starting verbs ('Implemented', 'Developed', 'Preprocessed'), but needs more outcome verbs." },
    { name: "Readability & Length", score: 92, weight: 10, status: "good", feedback: "Appropriate 1-page length for a junior candidate with balanced spacing." },
  ],
  detectedSections: [
    { name: "Contact Information", standard: true },
    { name: "Summary", standard: true },
    { name: "Education", standard: true },
    { name: "Technical Skills", standard: true },
    { name: "Projects", standard: true },
    { name: "Experience", standard: true },
  ],
  parseabilityFlags: {
    tablesDetected: false,
    multiColumnsDetected: false,
    nonStandardFonts: false,
    unusualSymbols: false,
  },
  issues: [
    {
      id: "ats-iss-1",
      category: "Metrics",
      severity: "critical",
      title: "Bullet Points Lack Measurable Results",
      description: "Recruiters and ATS parsing algorithms weight bullet points containing numbers, percentages, or scale metrics 40% higher.",
      suggestedFix: "Quantify the dataset scale and speed reduction in the Student Performance project.",
      beforeSnippet: "Preprocessed demographic and academic records across 1,000+ student profiles using Pandas.",
      afterSnippet: "Preprocessed 1,200+ multi-variable academic records using Pandas, reducing data pipeline runtime by 35% through vectorization.",
    },
    {
      id: "ats-iss-2",
      category: "Keywords",
      severity: "warning",
      title: "Missing Target Role Anchor Keywords",
      description: "For an AI Engineer application, keyword scanners specifically search for 'Model Evaluation', 'Inference', and 'API'.",
      suggestedFix: "Incorporate 'Model Evaluation' and 'Inference' directly into your project descriptions.",
      beforeSnippet: "Trained a machine learning pipeline on telecom customer logs to identify churn risk indicators.",
      afterSnippet: "Engineered and evaluated an end-to-end machine learning inference pipeline on 7,000+ customer records to predict churn probability.",
    },
    {
      id: "ats-iss-3",
      category: "Section",
      severity: "suggestion",
      title: "Missing Certifications or Online Coursework Section",
      description: "Including verified coursework or cloud certifications validates initiative outside university curriculum.",
      suggestedFix: "Add an 'Active Certifications & Coursework' block featuring ongoing PyTorch or AWS tracks.",
    },
  ],
};

export const mockJDComparison: JDComparison = {
  id: "jd-comp-001",
  targetRole: "Junior AI / ML Engineer",
  companyName: "NexusAI Technologies",
  seniority: "Entry-Level",
  overallMatch: 78,
  matchedRequirements: [
    { requirement: "Proficiency in Python and standard numerical libraries (NumPy, Pandas)", evidenceQuote: "Demonstrated across all coursework, internship, and project pipelines.", strength: "High" },
    { requirement: "Hands-on experience with classical ML algorithms (Classification, Regression)", evidenceQuote: "Trained Random Forest and Decision Tree models in churn and student projects.", strength: "High" },
    { requirement: "Relational database querying with SQL", evidenceQuote: "Extracted and cleaned telemetry data using SQL during DataCore internship.", strength: "High" },
    { requirement: "Git version control and collaborative code review", evidenceQuote: "GitHub profile and repository evidence provided.", strength: "Moderate" },
  ],
  missingCriticalRequirements: [
    "PyTorch or TensorFlow experience for neural network model development",
    "Containerization using Docker for model packaging and deployment",
    "RESTful API design (FastAPI/Flask) for serving real-time model inference",
  ],
  preferredRequirements: [
    "Cloud infrastructure experience with AWS (S3, EC2, SageMaker)",
    "Experience with experiment tracking tools such as MLflow or Weights & Biases",
  ],
  keywordGaps: [
    "PyTorch",
    "Docker",
    "FastAPI",
    "Containerization",
    "Inference Latency",
    "REST API",
    "CI/CD",
  ],
  priorityActions: [
    "Emphasize the Streamlit app's real-time prediction capability as an interactive inference interface.",
    "Add a dedicated bullet point mentioning ongoing PyTorch neural network projects.",
    "Include a target keyword section in your technical summary matching NexusAI's tech stack.",
  ],
  suggestedBulletTweaks: [
    {
      originalBullet: "Developed an interactive Streamlit web dashboard for real-time customer parameter simulation.",
      tailoredBullet: "Architected an interactive Streamlit inference dashboard serving real-time customer churn predictions with sub-second response times.",
      targetKeyword: "inference",
    },
    {
      originalBullet: "Trained a machine learning pipeline on telecom customer logs to identify churn risk indicators.",
      tailoredBullet: "Engineered an end-to-end ML classification pipeline on 7,000+ telecom logs, optimizing precision-recall tradeoffs for customer churn prediction.",
      targetKeyword: "pipeline optimization",
    },
  ],
};

export const mockProjectAnalyses: ProjectAnalysis[] = [
  {
    id: "pa-1",
    projectId: "proj-1",
    title: "Student Performance Prediction System",
    overallScore: 68,
    problemClarityScore: 85,
    technicalComplexityScore: 65,
    businessRelevanceScore: 60,
    technologyDepthScore: 70,
    mlAiDepthScore: 65,
    deploymentScore: 20,
    testingScore: 15,
    documentationScore: 75,
    starAlignmentScore: 60,
    starBreakdown: {
      situation: "Educational institutions require early warning systems to identify students at academic risk.",
      task: "Build predictive models forecasting final exam grades from demographic and study habits.",
      action: "Preprocessed 1,000+ student records with Pandas; trained Decision Tree and Random Forest Regressors.",
      result: "Not found in resume — lacking quantitative error metrics (RMSE/MAE) and deployment evidence.",
    },
    strengths: [
      "Clear problem statement and clean feature engineering with Pandas.",
      "Applied both decision trees and random forests with feature importance analysis.",
    ],
    weaknesses: [
      "No quantitative evaluation metrics reported (RMSE, MAE, R-squared).",
      "No web API or deployment artifact; script runs only in local Jupyter notebooks.",
      "No automated unit tests or input data validation.",
    ],
    recruiterQuestions: [
      "What was your model's Mean Absolute Error, and how did it compare against a baseline mean predictor?",
      "How did you address multicollinearity between study hours and prior semester grades?",
    ],
    improvementPlan: [
      "Compute and display R² and RMSE metrics in the project description.",
      "Export the trained model via ONNX or pickle and build a minimal FastAPI inference endpoint.",
      "Add input data validation with Pydantic.",
    ],
  },
  {
    id: "pa-2",
    projectId: "proj-2",
    title: "Customer Churn Classifier & Streamlit Dashboard",
    overallScore: 82,
    problemClarityScore: 90,
    technicalComplexityScore: 80,
    businessRelevanceScore: 90,
    technologyDepthScore: 80,
    mlAiDepthScore: 82,
    deploymentScore: 50,
    testingScore: 30,
    documentationScore: 85,
    starAlignmentScore: 85,
    starBreakdown: {
      situation: "Telecom providers experience revenue loss due to customer turnover without predictive retention triggers.",
      task: "Develop an automated classification pipeline to flag high-risk churn customers before contract expiration.",
      action: "Balanced dataset using SMOTE, trained Random Forest classifier, and built an interactive Streamlit UI.",
      result: "Achieved 83% validation ROC-AUC score and provided parameter-based simulation.",
    },
    strengths: [
      "Strong commercial relevance: customer churn is an industry-standard ML problem.",
      "Demonstrated understanding of class imbalance mitigation with SMOTE.",
      "Includes an interactive user interface via Streamlit.",
    ],
    weaknesses: [
      "Deployed only locally on localhost; lacks public cloud URL or Docker container.",
      "Does not discuss model interpretability (e.g., SHAP values for individual prediction explanations).",
      "Lacks automated CI/CD testing for model inference reliability.",
    ],
    recruiterQuestions: [
      "Why did you choose SMOTE over class weighting in the Random Forest loss function?",
      "In a telecom business setting, which is costlier: a False Positive or False Negative? How did that shape your threshold?",
    ],
    improvementPlan: [
      "Deploy the Streamlit app to Streamlit Community Cloud or Render and link the live URL.",
      "Incorporate SHAP or LIME waterfall plots in the UI to explain why individual customers were flagged.",
      "Containerize the application with a Dockerfile.",
    ],
  },
];

export const mockResumeImprovements: ResumeImprovement[] = [
  {
    id: "imp-1",
    section: "Summary",
    originalText:
      "Detail-oriented Artificial Intelligence & Data Science graduate with practical experience in Python, SQL, and applied machine learning. Passionate about developing data-driven predictive systems and seeking an AI Engineer or ML role to contribute to production environments.",
    suggestedText:
      "Artificial Intelligence & Data Science graduate with practical experience engineering Python ML pipelines and relational SQL queries. Proven track record training predictive models (83% ROC-AUC) and building interactive simulation dashboards. Seeking an entry-level AI/ML Engineer role to build production data and inference workflows.",
    reason:
      "Removes generic filler words ('Detail-oriented', 'Passionate') and substitutes concrete technical deliverables and verified project metrics.",
    confidence: 0.92,
    applied: false,
  },
  {
    id: "imp-2",
    section: "Experience",
    originalText:
      "Assisted senior engineers in extracting and cleaning structured customer telemetry data using SQL.",
    suggestedText:
      "Extracted and validated structured customer telemetry records using relational SQL, supporting data quality pipelines for senior engineering stakeholders.",
    reason:
      "Replaces passive phrasing ('Assisted senior engineers') with direct, impactful technical actions ('Extracted and validated', 'supporting data quality pipelines').",
    confidence: 0.88,
    applied: false,
  },
  {
    id: "imp-3",
    section: "Projects",
    originalText:
      "Preprocessed demographic and academic records across 1,000+ student profiles using Pandas.",
    suggestedText:
      "Engineered automated preprocessing pipelines for 1,000+ student records using Pandas, standardizing multi-variable distributions and eliminating missing data anomalies.",
    reason:
      "Elevates basic scripting into formal engineering vocabulary ('Engineered automated preprocessing pipelines', 'standardizing distributions').",
    confidence: 0.9,
    metricsMissingNotice: "Add a measurable runtime reduction if available.",
    applied: false,
  },
  {
    id: "imp-4",
    section: "Projects",
    originalText:
      "Trained a machine learning pipeline on telecom customer logs to identify churn risk indicators.",
    suggestedText:
      "Built and tuned a Random Forest machine learning pipeline on telecom logs, addressing class imbalance via SMOTE to reliably detect customer churn indicators.",
    reason:
      "Explicitly specifies the exact model family (Random Forest) and technique (SMOTE) directly in the opening bullet.",
    confidence: 0.94,
    applied: false,
  },
];

export const mockCareerRoadmap: CareerRoadmap = {
  id: "roadmap-demo-001",
  targetRole: "AI Engineer",
  durationWeeks: 12,
  currentStateSummary:
    "You have demonstrated proficiency in Python, Pandas, and basic Scikit-learn algorithms. To reach production AI Engineer competitiveness, this 12-week roadmap methodically bridges your PyTorch, Docker, FastAPI, and Cloud deployment gaps without overwhelming you.",
  immediatePriorities: [
    "Complete PyTorch neural network fundamentals & build first deep learning classifier.",
    "Package model into a FastAPI endpoint with Docker containerization.",
    "Deploy one public web inference project with GitHub Actions CI/CD.",
  ],
  milestones: [
    {
      id: "ms-1",
      phaseNumber: 1,
      phaseTitle: "Foundations",
      title: "PyTorch Deep Learning Core",
      duration: "Weeks 1 – 2",
      skills: ["PyTorch", "Tensors", "Custom Datasets", "Training Loops"],
      reason: "Closes the critical gap where deep learning is currently only a theoretical concept on your resume.",
      actionItems: [
        "Implement a custom PyTorch Dataset and DataLoader class.",
        "Code an end-to-end training loop with forward pass, loss calculation, backprop, and validation checkpointing.",
        "Train an image classification or text categorization model on a public Kaggle dataset.",
      ],
      recommendedProject: {
        name: "Medical Image or Audio Classifier in PyTorch",
        description: "Build a convolutional network with transfer learning using PyTorch torchvision models.",
        architecture: "PyTorch + Torchvision + TensorBoard for loss tracking.",
      },
      status: "in_progress",
    },
    {
      id: "ms-2",
      phaseNumber: 2,
      phaseTitle: "Production Serving",
      title: "Model Serving with FastAPI & Pydantic",
      duration: "Weeks 3 – 4",
      skills: ["FastAPI", "Pydantic", "REST APIs", "Async Python", "ONNX"],
      reason: "Industry recruiters evaluate whether you can make a trained model consumable by client applications.",
      actionItems: [
        "Wrap your PyTorch or Scikit-learn model in a RESTful FastAPI endpoint.",
        "Implement strict request/response data validation with Pydantic schemas.",
        "Add automated unit tests with PyTest checking prediction endpoints against edge-case payloads.",
      ],
      recommendedProject: {
        name: "High-Throughput ML Inference Microservice",
        description: "A standalone HTTP service that receives JSON telemetry and returns predictions with sub-50ms latency.",
        architecture: "FastAPI + Gunicorn/Uvicorn workers + PyTest test suite.",
      },
      status: "upcoming",
    },
    {
      id: "ms-3",
      phaseNumber: 3,
      phaseTitle: "Containerization",
      title: "Docker Containerization & Local Orchestration",
      duration: "Weeks 5 – 6",
      skills: ["Docker", "Dockerfiles", "Docker Compose", "Multi-stage builds"],
      reason: "Eliminates 'it runs on my machine' issues and fulfills a universal AI Engineer job requirement.",
      actionItems: [
        "Write a lean, secure multi-stage Dockerfile for your FastAPI ML service.",
        "Set up Docker Compose linking your API container to a PostgreSQL database container.",
        "Verify reproducible builds across different environments.",
      ],
      recommendedProject: {
        name: "Containerized Predictive Application",
        description: "Single-command `docker compose up` spinning up frontend, API, and database.",
        architecture: "Docker + Docker Compose + PostgreSQL + FastAPI.",
      },
      status: "upcoming",
    },
    {
      id: "ms-4",
      phaseNumber: 4,
      phaseTitle: "Cloud & CI/CD",
      title: "Cloud Deployment & GitHub Actions CI/CD",
      duration: "Weeks 7 – 8",
      skills: ["AWS / Render", "GitHub Actions", "CI/CD", "Environment Secrets"],
      reason: "Provides public proof of deployment that recruiters can click on directly from your resume header.",
      actionItems: [
        "Create a GitHub Actions workflow that runs PyTest on every Git push.",
        "Automate Docker image building on repository tagging.",
        "Deploy the containerized service to a cloud provider (Render, AWS EC2, or Fly.io).",
      ],
      recommendedProject: {
        name: "Live Cloud ML Service with CI/CD",
        description: "Production web endpoint with continuous integration badges on the GitHub README.",
        architecture: "GitHub Actions -> Docker Hub -> Cloud Web Service.",
      },
      status: "upcoming",
    },
    {
      id: "ms-5",
      phaseNumber: 5,
      phaseTitle: "Portfolio & Interview",
      title: "Portfolio STAR Evidence & Mock Interviews",
      duration: "Weeks 9 – 12",
      skills: ["STAR Technique", "System Design for ML", "Technical Communication"],
      reason: "Transforms your new technical artifacts into articulate, convincing interview storytelling.",
      actionItems: [
        "Rewrite resume bullet points with STAR structure incorporating verified cloud and Docker links.",
        "Practice mock interview simulations targeting the 3 common recruiter bottlenecks.",
        "Apply to 15+ tailored entry-level AI/ML roles with customized JD alignment.",
      ],
      status: "upcoming",
    },
  ],
};

export const mockInterviewSession: InterviewSession = {
  id: "session-demo-001",
  resumeId: "res-demo-001",
  targetRole: "AI Engineer",
  interviewType: "Technical",
  difficulty: "Entry/Fresher",
  status: "in_progress",
  questions: [
    {
      id: "q-1",
      orderIndex: 1,
      questionText:
        "In your Customer Churn project, you used a Random Forest classifier and handled class imbalance with SMOTE. Why did you choose SMOTE over adjusting class weights or downsampling, and what risk does synthetic oversampling introduce?",
      category: "Project & Modeling",
      difficulty: "Entry/Fresher",
      sourceContext: {
        type: "resume_project",
        detail: "Customer Churn Classifier with SMOTE",
      },
      expectedKeyPoints: [
        "SMOTE creates synthetic examples along feature space lines between minority samples.",
        "Adjusting class weights penalizes majority errors without adding data points.",
        "Risk: SMOTE can create noisy synthetic points in overlapping decision boundary regions.",
      ],
    },
    {
      id: "q-2",
      orderIndex: 2,
      questionText:
        "You listed strong proficiency in Pandas and Python data manipulation. Can you explain the difference between vectorization in NumPy/Pandas versus looping with `apply()`, and why it impacts inference latency?",
      category: "Python & Performance",
      difficulty: "Entry/Fresher",
      sourceContext: {
        type: "resume_skill",
        detail: "Python, Pandas & NumPy",
      },
      expectedKeyPoints: [
        "Vectorization executes operations in compiled C/C++ memory blocks without Python interpreter overhead.",
        "`apply()` incurs Python function call overhead for every row or element.",
        "In production inference, vectorization delivers 10x-100x speedups.",
      ],
    },
    {
      id: "q-3",
      orderIndex: 3,
      questionText:
        "Your resume targets an AI Engineer role, but does not list Docker or containerization. If you were asked to deploy your Scikit-Learn churn model into an existing microservices cluster today, what steps would you take to ensure reproducibility across machines?",
      category: "Target Role Gap",
      difficulty: "Entry/Fresher",
      sourceContext: {
        type: "role_gap",
        detail: "Missing Docker & Containerization for AI Engineer role",
      },
      expectedKeyPoints: [
        "Pin dependencies in requirements.txt or poetry.lock.",
        "Package the inference runtime and OS packages in a Docker container.",
        "Expose a lightweight HTTP API (FastAPI) listening on a designated port.",
      ],
    },
    {
      id: "q-4",
      orderIndex: 4,
      questionText:
        "Walk me through your Student Performance project using the STAR framework. Specifically, what was the primary quantifiable outcome, and how did you validate that your regression model wasn't overfitting to academic outliers?",
      category: "STAR & Metrics",
      difficulty: "Entry/Fresher",
      sourceContext: {
        type: "resume_project",
        detail: "Student Performance Prediction System",
      },
      expectedKeyPoints: [
        "Situation/Task: Academic risk identification.",
        "Action: Data cleaning, cross-validation, regularization.",
        "Result: Specific error metrics (MAE/RMSE) compared to baseline.",
      ],
    },
  ],
  evaluations: {
    "q-1": {
      questionId: "q-1",
      candidateAnswer:
        "I used SMOTE because our dataset had roughly an 80-20 split between non-churn and churned users, so simple training resulted in the model predicting the majority class. SMOTE synthesizes minority points by interpolating between nearest neighbors in feature space rather than duplicating data. The main risk is that if minority examples are located near noisy majority clusters, SMOTE can create unrealistic synthetic instances that blur the decision boundary.",
      technicalAccuracyScore: 92,
      clarityScore: 90,
      completenessScore: 88,
      projectUnderstandingScore: 95,
      conciseFeedback:
        "Excellent response! You accurately explained feature space interpolation between k-nearest neighbors and correctly identified boundary blurring as the primary failure mode.",
      strengths: [
        "Accurate definition of synthetic interpolation versus simple oversampling.",
        "Correctly recognized the risk of noise generation along decision boundaries.",
      ],
      improvementTips: [
        "You could also mention Borderline-SMOTE or combining SMOTE with Tomek links to clean boundary noise.",
      ],
      recruiterFollowUp:
        "How did you prevent synthetic points from leaking into your cross-validation folds during training?",
    },
  },
};

export const mockChatMessages: ChatMessage[] = [
  {
    id: "msg-1",
    role: "assistant",
    content:
      "Hello Alex! I am your CareerLens Copilot. I have thoroughly reviewed your resume, verified skills, and role benchmarks. You have a solid 84% fit for AI Engineer and an 89% fit for Data Analyst.\n\nHow can I help you today? You can ask me to explain your skill gaps, refine a project bullet point, or prepare you for an interview question.",
    timestamp: "10:30 AM",
    contextSources: [
      { type: "profile", title: "Alex Rivera Profile" },
      { type: "role_gap", title: "AI Engineer Role Match (84%)" },
    ],
  },
];

export const mockHistoryRecords: HistoryRecord[] = [
  {
    id: "hist-1",
    resumeVersion: "v1.2 (Current)",
    date: "Feb 15, 2025",
    filename: "Alex_Rivera_AI_Resume_2025.pdf",
    resumeScore: 78,
    atsScore: 76,
    topRole: "AI Engineer",
    roleMatch: 84,
    changeSummary: "Added Streamlit churn classifier and DataCore internship bullets.",
  },
  {
    id: "hist-2",
    resumeVersion: "v1.1",
    date: "Jan 10, 2025",
    filename: "Alex_Rivera_Resume_Jan2025.pdf",
    resumeScore: 68,
    atsScore: 70,
    topRole: "Data Analyst",
    roleMatch: 78,
    changeSummary: "Initial academic resume with Student Performance project only.",
  },
];
